### ISSUE TITLE
Multiline spec comments loose formatting

### ISSUE THREAD

**Issue by gberche-orange** [bosh-io/web#1]
Thanks again for putting together the bosh.io with job supported properties rendering. This is so useful.

Suggesting a small improvement to preserve formatting for multiline properties that use spaces for indentation:

https://github.com/cloudfoundry/cf-release/blob/master/jobs/login/spec#L192-L204
http://bosh.io/jobs/login?source=github.com/cloudfoundry/cf-release&version=212 property messages

**Comment by cppforlife** [comment]
Hmm. I believe paragraphs are maintained; however, this particular property content is hard to format properly. I think what should be done in this case is to add `example` key next to description (like in  http://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=0.56.0).

**Comment by gberche-orange** [comment]
Thanks Dmitry. Does the bosh Spec file support multiple example keys for the same property (which is the case for the login.messages (one flat and one nested example)

I was trying to answer that from the bosh-docs but did not find it yet from https://bosh.io/docs/create-release.html#create-props Is the Spec file format described somewhere else ? I searched the answer into the bosh source code but did not yet find it.

I'd be happy to send PRs to bosh-docs to improve that with that and to the cf-release to use this example syntax.

**Comment by cppforlife** [comment]
You can only provide single example. I think it's best for UAA team to decide what should be the format for these message and recommend to accept it only one way.

`example` key is not used by BOSH itself and is only consumed by this site when showing job properties. I have not rewritten release creation docs yet so it's not mentioned there either.
