### ISSUE TITLE
Stemcells should have SHA-2 displayed instead of/in addition to SHA-1

### ISSUE THREAD

**Issue by amitkgupta** [bosh-io/web#17]

**Comment by friegger** [comment]
The same should be in place for releases, at least if they provide SHA-2. The core bosh releases should provide it.

**Comment by sklevenz** [comment]
Is there a chance to get this issue into focus? SHA-1 is not accepted for use cases that require regulatory compliance.

**Comment by ramonskie** [comment]
created a PR https://github.com/bosh-io/web/pull/52
