### ISSUE TITLE
New versions of releases not on master branch should show up on bosh.io

### ISSUE THREAD

**Issue by amitkgupta** [bosh-io/web#18]
Should be able to cut releases on LTS branches without having to do weird git things for them to show up on bosh.io.

/cc @ishustava @iredelmeier

**Comment by cppforlife** [comment]
no plans for this issue. expectation is that there is a single place for consumers to grab all release versions (default branch). alternative solution is to have a separate repo that keeps the release metadata (can be achieved by using `bosh finalize-release ...` command)
