### ISSUE TITLE
bosh-io worker pulled release duplicated versions

### ISSUE THREAD

**Issue by edwardstudy** [bosh-io/web#38]
HI, I am dev for SL CPI. And I pulled new CPI NG for bosh.io.

These are my issues:

1. When the latest version was v30, I could not push old [v24](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/releases/tag/v24) for backporting. How could I push older release for SL CPI?
2. I made a mistake to let concourse push the v31 release from its cache, so I removed the wrong release and updated correct v31. So worker pulled two v31 releases: https://github.com/bosh-io/releases-index/commit/3d8cb714a9048cc241cbb87d45d6f085ecf07e83. Could you help us to remove v31 release

Currently, [bosh.io for SL CPI](https://bosh.io/releases/github.com/cloudfoundry/bosh-softlayer-cpi-release?all=1) could not access due to I removed all v31 releases:

> template: layout:197:5: executing "layout" at <yield>: error calling yield: template: releases/_usage:6:12: executing "releases/_usage" at <.TarballSHA1>: error calling TarballSHA1: Finding release version: <nil cause>

Thank you!

**Comment by dpb587-pivotal** [comment]
Hi,

1. bosh.io only monitors the `release` directory for finalized releases. It looks like you tagged v24, but the finalized metadata is not available on the `master` branch. If you want it to show up, you'll need to finalize the release there.

2. bosh.io currently does not support releases with multiple names, so it was erroring on the `*-ng` version of the release. I [manually removed](https://github.com/bosh-io/releases-index/commit/4305cc87484ef50a6e7ab5f2ec9aecc5c2b3722e) the bad v31, but this is not something we should do again. Please be sure to fix the related automation steps to avoid this in the future.

cc @jfmyers9
