### ISSUE TITLE
Command to download stemcell has incorrect SHA in cases where a light stemcell exists

### ISSUE THREAD

**Issue by skibum55** [bosh-io/web#39]
In the cases where there is a light stemcell you seem to be using the sha1 for it instead of the one for the full stemcell.  It seems to be the case for AWS, GCP.  I'm not a go person, but I believe it's somewhere around here https://github.com/bosh-io/web/blob/master/templates/stemcells/single.tmpl#L14
<img width="750" alt="screen shot 2018-08-21 at 10 02 18 pm" src="https://user-images.githubusercontent.com/3813241/44442291-731cb380-a58e-11e8-8bef-3ee00f87a315.png">

**Comment by dpb587-pivotal** [comment]
By default, those `bosh.io/d/stemcells/...` links redirect to the light stemcells, so the listed checksum should be correct.

I manually tried downloading from those links and verifying the `--sha1` checksum and it matched. Are you seeing a particular error somewhere?

**Comment by skibum55** [comment]
We were getting an error.  But I can't reproduce it now.
