### ISSUE TITLE
Support serving releases and stemcells over http as to support caching

### ISSUE THREAD

**Issue by gberche-orange** [bosh-io/web#41]
As a bosh user, in order to speed up bosh deployments dependent on remote internet stemcells/releases, I would like that URLs served by bosh.io for releases and stemcells to be cacheable by intermediate caches (such as a corporate http proxy). Bosh director does support explicit [http proxy](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=268.4.0#p%3denv) (or could use transparent caching proxies) for downloading releases and stemcells.

Releases and stemcells can be downloaded and their sha checksum checked (see https://bosh.io/docs/release-urls/#http), through urls served by bosh.io such as https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=12 . Bosh.io currently does a 302 redirect 

In order for an intermediate proxy server to cache release and stemcells, the URLs can't use the HTTPS scheme and instead use plain http scheme.

Currently, bosh.io seems to only redirect releases and stemcells endpoints such as https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=12 to HTTPS urls on AWS S3.

```
> GET /d/github.com/cloudfoundry/os-conf-release?v=12 HTTP/1.1
> Host: bosh.io
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Fri, 18 Jan 2019 16:01:18 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 907
< Connection: keep-alive
< Location: https://dfdtmjpfvu0dy.cloudfront.net/c9081528-d29c-4b09-555d-96702d704faa?response-content-disposition=attachment%3B%20filename%3Dos-conf-release-12.tgz&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kZmR0bWpwZnZ1MGR5LmNsb3VkZnJvbnQubmV0L2M5MDgxNTI4LWQyOWMtNGIwOS01NTVkLTk2NzAyZDcwNGZhYT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0IlMjBmaWxlbmFtZSUzRG9zLWNvbmYtcmVsZWFzZS0xMi50Z3oiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDc4Mjc4Nzh9fX1dfQ__&Signature=YxLD8IYlFLxTQVbpGDxyx6~vhwEOI20w67LduarhrKBKmh7F5WeUJU8HvjlSOJ3fR9DK5PwPwiDaobg46GG7-PzYoQnFXsPzcN-YzUa35ywH9Jpprdjowt~dThDKccd9duBOLNsUx4t8Jc2GtarGGweiu9Q5-nACOPi0AVfHefEU9m0NGpsbKJd68qjNK~cqskje6XNvaV~5ebps8aHvx~9KSyTXi3hITSmtHaLsoFWob0wBeWcBZ9FrNsjq~u0CD7JQfJC56f50Xa-1SsEu7zEW6yaYFCQWfAl8hONTORaKZXoSr0Cd7oXXqF0npVOrAnOluOciKSigUFwWMJDNzw__&Key-Pair-Id=APKAICIFS42OUZR7AVEQ
[...]
```

Possible implementations:
- add a new query param (e.g "plainHttp=true|false") that would redirect to plain http url instead of https url.

https://github.com/bosh-io/web/blob/eafa2223d47ccb3078204ed77e0940eb5ab84693/controllers/releases_controller.go#L88-L111
- when the releases and stemcells endpoints are accessed through plain http, redirect to HTTP S3 urls instead of HTTPS urls. Keep redirection to HTTPS S3 urls when bosh.io endpoints are accessed over https

**Comment by dpb587-pivotal** [comment]
Hi - would you mind providing a bit more context in where these uploads are coming up? More specifically, I would rather we first find ways to reduce the needs for downloads to occur at all, cached or not.

It looks like you've referenced this from the cf-deployment workflow. The CLI should avoid uploading releases which the director already knows about. The `use-compiled-releases.yml` ops file uses the `stemcell` field which should help avoid duplicate uploads as well.

Or perhaps you're suggesting that you repeatedly run these deployment operations across environments which each need the bytes and are looking to optimize locally with a caching server?

**Comment by heyjcollins** [comment]
cc @heyjcollins

**Comment by dpb587-pivotal** [comment]
Hi @gberche-orange, the teams have chatted about this a little bit, and I don't think we want to support the changes you're describing for a few reasons. One general principal is that all connections should be encrypted, regardless of content or other content verifications that may be happening (like BOSH doing checksums). We store our assets via HTTPS, we should really be giving them back to users as HTTPS and not trying to manipulate storage URLs. Another complicating factor is that proxies often have a size limit of what they will cache; this will eventually lead to mixed and, likely, surprising behavior to operators who are unaware of this, eventually leading to debates between IT Ops and BOSH Ops.

That being said, I understand the use case and do think it's valid and reasonable. As a more general solution, what I've done in similar cases is to recommend setting up your own reverse proxy server with caching enabled. This gives you proper control on how large of assets and which kind of assets you're interested in keeping for your environments. You can do this with a fairly short `nginx` configuration and update your release URL references to point to your mirror with `sed` or ops files.

If you're interested in other mirroring strategies for BOSH assets, I'd be interested to chat more. It's not something we currently, officially support, but I'd be interested to learn how you'd identify which assets are worth mirroring.

Let me know if you want to discuss this more.

**Comment by gberche-orange** [comment]
thanks @dpb587-pivotal for considering this feature proposal. While I acknowledge the team decision some comments over its rationales:

> One general principal is that all connections should be encrypted, regardless of content or other content verifications that may be happening (like BOSH doing checksums).

Using TLS for downloading content provides two benefits:
1. authenticating the server
1. preserving confidentially of the downloaded content.
1. preventing MITM trying to serve forged content

For bosh.io download urls the content is public. So 2) does not seem necessary. 1) and 3) are covered by bosh director checking content checksums

> We store our assets via HTTPS, we should really be giving them back to users as HTTPS and not trying to manipulate storage URLs.

Did you mean `We upload our assets into S3 securely using TLS, we should really be serving them to users with TLS, and not allow users to opt-in for downloading content over plain http` ?

> Another complicating factor is that proxies often have a size limit of what they will cache; this will eventually lead to mixed and, likely, surprising behavior to operators who are unaware of this, eventually leading to debates between IT Ops and BOSH Ops.

In our case, we're running dedicated proxies for bosh downloads, with proper control over [max cached size](http://www.squid-cache.org/Doc/config/maximum_object_size/) or [cache exclusion patterns](https://serverfault.com/questions/163130/best-way-to-bypass-squid-for-certain-sites)

> As a more general solution, what I've done in similar cases is to recommend setting up your own reverse proxy server with caching enabled. This gives you proper control on how large of assets and which kind of assets you're interested in keeping for your environments.

> You can do this with a fairly short `nginx` configuration and update your release URL references to point to your mirror with `sed` or ops files.

I understand that in current state of ops files syntax, ops file can only replace complete yml key/value but not perform transformations on a given value content (such as a regexp) and that most manifests directly reference bosh.io urls. This would therefore require bosh manifest files preprocessing step that would need to be included in associated tooling such as bbl.
* https://bosh.io/docs/cli-ops-files/
* https://github.com/cppforlife/go-patch/blob/master/patch/replace_op_test.go

However, @heyjcollins could recommend best way to reference mirrored bosh.io bosh-releases and stemcells URIs in cf-deployment, or consider a future native support for it.

**Comment by gberche-orange** [comment]
@bosh-admin-bot please keep this issue open as I believe it is still relevant
