### ISSUE TITLE
Unable to build project locally due to unresolvable dependencies

### ISSUE THREAD

**Issue by dave-malone** [bosh-io/web#5]
The following dependencies could either be remediated, or this project could use Godeps to vendor all of the versions that are currently being used to simplify checking out this project for the first time. 
1. Dependency on code.google.com/p/go-charset/charset can't be resolved because this dependency is no longer go "gettable"
2. Package github.com/cloudfoundry/bosh-agent/blobstore has been relocated to github.com/cloudfoundry/bosh-utils/blobstore
3. Package github.com/cloudfoundry/bosh-agent/errors has been relocated to github.com/cloudfoundry/bosh-utils/errors
4. Package github.com/cloudfoundry/bosh-agent/logger has been relocated to github.com/cloudfoundry/bosh-utils/logger
5. There are a number of other dependencies on the old github.com/cloudfoundry/bosh-agent/\* packages which have all been relocated to github.com/cloudfoundry/bosh-utils
6. Packages in dependency cppforlife/bosh-provisioner/\* also depend on packages that have been relocated from the bosh-agent repo to the bosh-utils project

**Comment by skibum55** [comment]
I believe this pull request from @voelzmo has updated the dependencies https://github.com/cppforlife/bosh-hub/pull/6

**Comment by cppforlife** [comment]
moved to bosh-io org and resolved.
