### ISSUE TITLE
Permalink to latest bosh-init for a platform

### ISSUE THREAD

**Issue by wendorf** [bosh-io/web#8]
The [bosh-init documentation](https://bosh.io/docs/install-bosh-init.html) provides a helpful link to the latest version, but I would like to write a script that automatically gets the latest version and uses it. If there were a permalink that is always the latest version (e.g. http://bosh.io/bosh-init-latest-darwin-amd64 instead of https://s3.amazonaws.com/bosh-init-artifacts/bosh-init-0.0.81-darwin-amd64), that would be very helpful.

Thanks!

**Comment by shalako** [comment]
I've been opening a similar issue on the `bbl` and `bosh cli v2` repos, and was about to do the same for `bosh-init`. Then I thought how bosh.io could provide permalinks so teams wouldn't have to.

**Comment by dpb587-pivotal** [comment]
Closing - bosh-init is no longer supported.
